export type Category = "Food" | "Drinks" | "Dessert" | "Other";

export type Deal = {
  id: string;
  name: string;
  category: Category;
  freebie: string;
  conditions?: string;
  image?: string;

  // Optional “better maps” + detail page extras
  mapQuery?: string;      // e.g. "Starbucks" or "Starbucks coffee"
  signupUrl?: string;     // e.g. rewards signup link
  claimSteps?: string[];  // bullet steps for detail page
};

export const ALL_DEALS: Deal[] = [
  {
  id: "starbucks",
  name: "Starbucks",
  category: "Drinks",
  freebie: "Free birthday drink",
  conditions: "Requires Starbucks Rewards",
  mapQuery: "Starbucks",
  signupUrl: "https://www.starbucks.com/rewards",
  claimSteps: [
    "Join Starbucks Rewards",
    "Add your birthday",
    "Redeem in app or in-store",
  ],
  image: "/deals/starbucks.png",
},

  {
    id: "chipotle",
    name: "Chipotle",
    category: "Food",
    freebie: "Birthday reward (varies)",
    conditions: "Must be enrolled in rewards",
    mapQuery: "Chipotle",
    signupUrl: "https://www.chipotle.com/chipotle-rewards",
    claimSteps: [
      "Join Chipotle Rewards",
      "Make sure your birthday is saved in your account",
      "Check rewards around your birthday and redeem",
    ],
    image: "/deals/chipotle.png",
  },
  {
    id: "nothingbundt",
    name: "Nothing Bundt Cakes",
    category: "Dessert",
    freebie: "Free bundtlet",
    conditions: "Join email list",
    mapQuery: "Nothing Bundt Cakes",
    signupUrl: "https://www.nothingbundtcakes.com/",
    claimSteps: [
      "Sign up for emails / rewards (varies by location)",
      "Add your birthday info when prompted",
      "Redeem your birthday offer in-store",
    ],
    image: "/deals/nothingbunt.png",
  },
  {
    id: "krispykreme",
    name: "Krispy Kreme",
    category: "Dessert",
    freebie: "Free Original Glazed donut",
    conditions: "Requires Krispy Kreme Rewards",
    mapQuery: "Krispy Kreme",
    signupUrl: "https://www.krispykreme.com/rewards",
    claimSteps: ["Join rewards", "Add birthday", "Redeem in store or app"],
    image: "/deals/krispy.png",
  },
  {
    id: "panera",
    name: "Panera Bread",
    category: "Food",
    freebie: "Birthday treat (varies)",
    conditions: "MyPanera member required",
    mapQuery: "Panera Bread",
    signupUrl: "https://www.panerabread.com/en-us/mypanera.html",
    claimSteps: ["Create MyPanera account", "Add birthday", "Check rewards on your birthday"],
    image: "/deals/panera.png",
  },
  {
    id: "sephora",
    name: "Sephora",
    category: "Other",
    freebie: "Free birthday gift",
    conditions: "Beauty Insider member required",
    mapQuery: "Sephora",
    signupUrl: "https://www.sephora.com/beauty/beauty-insider",
    claimSteps: ["Join Beauty Insider", "Redeem in store or online during birthday month"],
    image: "/deals/sephora.png",
  },
  {
    id: "ulta",
    name: "Ulta Beauty",
    category: "Other",
    freebie: "Free birthday gift + bonus points",
    conditions: "Ultamate Rewards member required",
    mapQuery: "Ulta Beauty",
    signupUrl: "https://www.ulta.com/rewards/all",
    claimSteps: ["Join Ultamate Rewards", "Add birthday", "Redeem gift in store during birthday month"],
  },
  {
    id: "ihop",
    name: "IHOP",
    category: "Food",
    freebie: "Free birthday pancakes",
    conditions: "IHOP Rewards required",
    mapQuery: "IHOP",
    signupUrl: "https://www.ihop.com/en/rewards",
    claimSteps: ["Join rewards", "Add birthday", "Redeem offer in app"],
    image: "/deals/ihop.png",
  },
  {
    id: "jerseymikes",
    name: "Jersey Mike’s",
    category: "Food",
    freebie: "Birthday sub reward (varies)",
    conditions: "Shore Points member required",
    mapQuery: "Jersey Mike's",
    signupUrl: "https://www.jerseymikes.com/rewards",
    claimSteps: ["Join Shore Points", "Add birthday", "Redeem reward when it appears"],
    image: "/deals/jerseymikes.png",
  },
  {
    id: "bathbodyworks",
    name: "Bath & Body Works",
    category: "Other",
    freebie: "Birthday reward (varies)",
    conditions: "Rewards member required (where available)",
    mapQuery: "Bath & Body Works",
    signupUrl: "https://www.bathandbodyworks.com/my-account/rewards",
    claimSteps: ["Join rewards", "Add birthday", "Check app for birthday offer"],
    image: "/deals/bnb.png",
  },
  {
    id: "coldstone",
    name: "Cold Stone Creamery",
    category: "Dessert",
    freebie: "Buy-one-get-one treat (varies)",
    conditions: "My Cold Stone Club required",
    mapQuery: "Cold Stone Creamery",
    signupUrl: "https://www.coldstonecreamery.com/about/clubs/",
    claimSteps: ["Join the club", "Confirm email", "Get coupon near your birthday"],
    image: "/deals/coldstone.png",
  },
  {
    id: "jeremias",
    name: "Jeremiah’s Italian Ice",
    category: "Dessert",
    freebie: "Free birthday treat (varies)",
    conditions: "Rewards member required",
    mapQuery: "Jeremiah's Italian Ice",
    signupUrl: "https://jeremiahsice.com/rewards/",
    claimSteps: ["Join rewards", "Add birthday", "Redeem offer in store"],
    image: "/deals/jeremiahs.png",
  },
  {
    id: "cinnabon",
    name: "Cinnabon",
    category: "Dessert",
    freebie: "Birthday reward (varies)",
    conditions: "Cinnabon Rewards required",
    mapQuery: "Cinnabon",
    signupUrl: "https://www.cinnabon.com/rewards",
    claimSteps: ["Join rewards", "Add birthday", "Redeem in app"],
    image: "/deals/cinnabon.png",
  },
  {
    id: "raisingcanes",
    name: "Raising Cane’s",
    category: "Food",
    freebie: "Birthday reward (varies)",
    conditions: "Cane’s rewards member required",
    mapQuery: "Raising Cane's",
    signupUrl: "https://www.raisingcanes.com/canes-rewards/",
    claimSteps: ["Join rewards", "Add birthday", "Redeem reward when available"],
  image: "/deals/canes.png",
  },
  {
    id: "buffalowildwings",
    name: "Buffalo Wild Wings",
    category: "Food",
    freebie: "Birthday reward (varies)",
    conditions: "Rewards member required",
    mapQuery: "Buffalo Wild Wings",
    signupUrl: "https://www.buffalowildwings.com/rewards/",
    claimSteps: ["Join rewards", "Add birthday", "Check app for birthday reward"],
  image: "/deals/bww.png",
  },
];
