// app/layout.tsx
// Root layout for the entire app
// Sets up global fonts, metadata, and base HTML structure

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Load Geist Sans and expose it as a CSS variable
// This lets Tailwind and plain CSS reference the font consistently
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Load Geist Mono for code / mono contexts
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Default metadata applied to all pages
// Can be overridden by individual routes if needed
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Root HTML wrapper for the app
    <html lang="en">
      <body
        // Apply font CSS variables globally
        // `antialiased` improves text rendering across devices
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Render the active route */}
        {children}
      </body>
    </html>
  );
}
